In [2]:
import numpy as np #here np is alais name
#creating an arrray
a=np.array([1,2,34,5])
print(a)
 #we also create array within particular range 
b=np.arange(10,16)
print(b)

[ 1  2 34  5]
[10 11 12 13 14 15]


In [7]:
# import numpy as np

# A = np.array([[30,31,40], [41,50,51], [60,61,70]])

# print(np.linalg.det(A))
# import numpy as np

# A = np.array([[20,10],[50,10]])

# print("\nTrace of A:", np.trace(A))
import numpy as np

# A = np.array([[-3,2,-5],[2,-3,4],[1,1,1]])

# B = np.array([[3,2],[1,4],[5,3]])

# C = np.dot(A,B)

# C.shape
# import numpy as np

# a = np.array([[2,3],[5,-4]])

# b = np.array([20,27])

# res = np.linalg.solve(a,b)

# print(res)
import numpy as np 
# A = np.array([[55,5],[35,15]])

# eig_val,eig_vec = np.linalg.eig(A)

# print('Eigen values\n',eig_val)

# print('Eigen vector\n',eig_vec)
A = np.array([[1,2],[3,4]])

print(np.linalg.det(A))

-2.0000000000000004


In [5]:
# creating zero value array
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#creating 1 value array
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#creating  from list ,tuplee
list=[1,2,3,4,5,6]
tup=(1,2,3,4,5,7)
l=np.array(list)
print(l)
t=np.array(tup)
print(t)


[1 2 3 4 5 6]
[1 2 3 4 5 7]


In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print(a.size)
print(a.ndim)
print(a.shape)
print(a.dtype)

# we can also change the shape of an array
#for that purspose the shape is between the factor of size
a.shape=(6,2)
print(a)

print('or we can directly use reshpae() at the time of creatiom')
c=np.array([12,1,3,4,5,6,7,8,8,91,11,12]).reshape(3,4)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
12
2
(4, 3)
int32
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
or we can directly use reshpae() at the time of creatiom
[[12  1  3  4]
 [ 5  6  7  8]
 [ 8 91 11 12]]


In [31]:
#Broadcasting an array
list=[1,2,3,4,5,6]
tup=(1,2,3,4,5,7)
l=np.array(list)
t=np.array(tup)

#c=l+t
c=l*t
print(c)

[ 1  4  9 16 25 42]


In [32]:
#broadcasting nd array
#here the array must be same dimension foe any operations
#the operations are performed element wise not matrix wise
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print(x+y)

[[ 8 10 12]
 [14 16 18]]


In [42]:
#Generating linerly spaced elemnts 
z=np.linspace(10,30,5, dtype=int)
#here the array is generated from range 10 to 30 with size of 5
#the default datatype is float 
#u can change it using dtype= data type name
print(z)
y=np.linspace(10,30,5, dtype=int, retstep=True)
#the retstepis used to get linear difference betwenn them
print(y)


[10 15 20 25 30]
(array([10, 15, 20, 25, 30]), 5.0)


In [48]:
#view() and copy()
a=np.array([1,2,3,4,5,5])

a1=np.copy(a)
#if we cange some value in array wont reflect in copy
a[4]=3
print(a)
print(a1)





[1 2 3 4 3 5]
[1 2 3 4 5 5]


In [51]:
#the view araay also used to copy the array but any changes happen in array or copy of an array it we made to array
ba=np.array([1,2,3,4,5,5])
print(a)
ba1=ba.view()
print(ba1,"\n")

ba[4]=3
print(ba)
print(ba1)

[1 2 3 4 3 5]
[1 2 3 4 5 5] 

[1 2 3 4 3 5]
[1 2 3 4 3 5]


In [54]:
#we can also create array from random elements\
a=np.random.random()
print(a)
#genrate random elemnts ranging from 0 to 1

0.8002197899713684


In [55]:
x=np.random.randint(10,20)
print(x)
#generate the array ement in range 10 and 20

16


In [57]:
z=np.random.randint(10,30,5)
#genrated random array of size 5
print(z)

[23 28 23 19 25]


In [66]:
s=np.random.choice([1,2,3,4,5,6,7], size=3)
print(s)
#give random sample from 1d array odf mentiones size

[3 3 6]


Slicing in Numpy Arrays

In [19]:
#slicing in numppy arrays it used to iterate ove rthe arrays
#a[star:end:step]
import numpy as np 
a=np.array([20 ,21, 22, 23, 24, 25 ,26 ,27 ,28 ,29])
print(a)
print(a[::2])
print(a[::-1])#reverse 
print(a[-1])
print(a[-5])
print(a[3:-3])
print(a[-2:-8:-2])




[20 21 22 23 24 25 26 27 28 29]
[20 22 24 26 28]
[29 28 27 26 25 24 23 22 21 20]
29
25
[23 24 25 26]
[28 26 24]


In [61]:
#slicing with the numpy array
d=np.arange(31,47).reshape(4,4)
print(d)

print(d[1][2])
print(d[-2:,-2:],"\n")
print(d[-3,-3],d[-2,-1],"\n")
print(d[:2:-1,2::],"\n")
print(d[:1:-1,:3],"\n")
print(d[0::3,0::3],"\n")
print(d[-1::-3,-1::-3],"\n")
print(d[1::2,3])
print(d[-3::-1,-3])


[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
37
[[41 42]
 [45 46]] 

36 42 

[[45 46]] 

[[43 44 45]
 [39 40 41]] 

[[31 34]
 [43 46]] 

[[46 43]
 [34 31]] 

[38 46]
[36 32]


In [70]:
d=np.arange(31,47).reshape(4,4)
print(d)

print(d[::2,::2],"\n")
print(d[1:,2:],"\n")
print(d[::2,:],"\n")
print(d[1:,3:],"\n")
print(d[1:3,1:3],"\n")
print(d[-2::-2,-1:0:-1])
print(d[[0,1,1],[0,1,2]])

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
[[31 33]
 [39 41]] 

[[37 38]
 [41 42]
 [45 46]] 

[[31 32 33 34]
 [39 40 41 42]] 

[[38]
 [42]
 [46]] 

[[36 37]
 [40 41]] 

[[42 41 40]
 [34 33 32]]
[31 36 37]


--------------------------------------Array Operations using Numpy--------------------------------

Sum() 

In [14]:
import numpy as np 
a=np.array([[12,13,14],[12,13,14]])
print(a,"\n")
#Np.sum() can perform the addition of all the elemnts in the array
sum=np.sum(a)
print(sum,"\n")

#lets try 3D array
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
b=np.array(list).reshape(2,4,2)
print(b)

sum3D=np.sum(b)
print(sum3D)



[[12 13 14]
 [12 13 14]] 

78 

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
136


MIN() AND MAX()

In [23]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr=np.array(list).reshape(4,4)
print(arr)

#Finding minimun in entire array
print("The mimimum elemnt is",np.min(arr))
print("The maximun element is",np.max(arr),"\n")

#finding max and min row wise
print("The minimun elemnt in each row",arr.min(axis=1))
print("The maximum elelemnt in each row",arr.max(axis=1),"\n")

#finding max and min column wise
print("The minimun elemnt in each column",arr.min(axis=0),)
print("The maximum elelemnt in each column",arr.max(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The mimimum elemnt is 1
The maximun element is 16 

The minimun elemnt in each row [ 1  5  9 13]
The maximum elelemnt in each row [ 4  8 12 16] 

The minimun elemnt in each column [1 2 3 4]
The maximum elelemnt in each column [13 14 15 16]


argmin() and argmax()  This return the indices of the manimum and maximum elemts in an array

In [28]:
list=[11,23,44,5,66,87,11,42,77,25,12,22,13,56,8,16]
arr=np.array(list).reshape(4,4)
print(arr)

#Finding minimun in entire array
print("The mimimum elemnt is",np.min(arr))
print("The index of minimum element is",np.argmin(arr),"\n")

print("The maximun element is",np.max(arr))
print("The index of maximum element is",np.argmax(arr),"\n")

#finding max and min row wise
print("The minimun elemnt in each row",arr.min(axis=1))
print("The indeices of minimun elemnt in each row",arr.argmin(axis=1),"\n")

print("The maximum elelemnt in each row",arr.max(axis=1))
print("The indices of maximum elemnt in each row",arr.argmax(axis=1),"\n")

#finding max and min column wise
print("The minimun elemnt in each column",arr.min(axis=0))
print("The indeices of minimun elemnt in each column",arr.argmin(axis=0),"\n")

print("The maximum elelemnt in each column",arr.max(axis=0))
print("The indices of maximum elemnt in each colimn",arr.argmax(axis=0),"\n")

[[11 23 44  5]
 [66 87 11 42]
 [77 25 12 22]
 [13 56  8 16]]
The mimimum elemnt is 5
The index of minimum element is 3 

The maximun element is 87
The index of maximum element is 5 

The minimun elemnt in each row [ 5 11 12  8]
The indeices of minimun elemnt in each row [3 2 2 2] 

The maximum elelemnt in each row [44 87 77 56]
The indices of maximum elemnt in each row [2 1 0 1] 

The minimun elemnt in each column [11 23  8  5]
The indeices of minimun elemnt in each column [0 0 3 0] 

The maximum elelemnt in each column [77 87 44 42]
The indices of maximum elemnt in each colimn [2 1 0 1] 



sort()  used to sort arrys in numpy

In [38]:
list=[11,23,44,5,66,87,11,42,77,25,12,22,13,56,8,16]
d=np.array(list).reshape(4,4)
print(d,"\n")


#sorting an array
print("By default elemts are sorted row wise ")
print(np.sort(d),"\n")

#sorting an array row wise
print("The elements in array are sorted row wise")
print(np.sort(arr,axis=1),"\n")

print("sorting array elemnts column wise")
print(np.sort(arr,axis=0))


[[11 23 44  5]
 [66 87 11 42]
 [77 25 12 22]
 [13 56  8 16]] 

By default elemts are sorted row wise 
[[ 5 11 23 44]
 [11 42 66 87]
 [12 22 25 77]
 [ 8 13 16 56]] 

The elements in array are sorted row wise
[[ 5 11 23 44]
 [11 42 66 87]
 [12 22 25 77]
 [ 8 13 16 56]] 

sorting array elemnts column wise
[[11 23  8  5]
 [13 25 11 16]
 [66 56 12 22]
 [77 87 44 42]]


where()  return the index number for maching conditio

In [45]:
b=np.arange(10,22)
b.shape=(4,3)
print(b,"\n")

#suppose we wat to find the ood number then we simply apply the condtion in where()
#so that where () gives index where these elents are present 
odd=np.where(b%2!=0)
print(odd,"\n")

#give the elemets in array which are greather than 15 
#where() gives the index where these elemets present
print(np.where(b>15))
print("\n")


#we can also give three parametrs whicg return the modified vales
#if b<15 add 5 to to values else multiply it by 2

ans=np.where(b<15,b+5,b*2)
print(ans)



[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 

(array([0, 1, 1, 2, 3, 3], dtype=int64), array([1, 0, 2, 1, 0, 2], dtype=int64)) 

(array([2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))


[[15 16 17]
 [18 19 30]
 [32 34 36]
 [38 40 42]]


extract()  directly returns the values in the condition applied array

In [54]:
#it takes two parameters one is condition and second the array on which condtion should be applied
b=np.arange(10,22)
b.shape=(4,3)
print(b,"\n")


#we can print values in array which are even
print(np.extract(b%2==0,b),"\n")


#we can get values greather than 15
print(np.extract(b>15,b))

#we can increment the values in array

print(np.extract(b%3==0,b))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 

[10 12 14 16 18 20] 

[16 17 18 19 20 21]
[12 15 18 21]


Numpy Concatenate() function


In [1]:
import numpy as np 
#concatenate() used to cobime the two arrays 
a1=np.array([22,3,41,55,7])
a2=np.array([11,16,39,38,4])

b1=np.concatenate([a1,a1])
print(b1)
print("\n")


b2=np.concatenate([a2,a1])
print(b2)

[22  3 41 55  7 22  3 41 55  7]


[11 16 39 38  4 22  3 41 55  7]


In [3]:
#concatenate() for 2D array

d1=np.array([[22,33,11,99],[44,77,45,2]])
d2=np.array([[1,2,3,4],[5,6,7,8]])

#the one array concatenated other by column wise .
ans=np.concatenate([d1,d2],axis=0)
print(ans,"\n")

#one array is concatenated to other row wise
ans1=np.concatenate([d1,d2],axis=1)
print(ans1)


[[22 33 11 99]
 [44 77 45  2]
 [ 1  2  3  4]
 [ 5  6  7  8]] 

[[22 33 11 99  1  2  3  4]
 [44 77 45  2  5  6  7  8]]


hstack() ans vstack()   Stacks the array horizontally and vertically res.

In [6]:
import numpy as np 

d1=np.array([[22,33,11,99],[44,77,45,2]])
d2=np.array([[1,2,3,4],[5,6,7,8]])


#hstack()-- the new row are created  horizontaly placed infont of existing array row
hstak=np.hstack((d1,d2))
print(hstak,"\n")


#vstack -- the colums are created right below the existing array columns
vstack=np.vstack([d1,d2])
print(vstack)


[[22 33 11 99  1  2  3  4]
 [44 77 45  2  5  6  7  8]] 

[[22 33 11 99]
 [44 77 45  2]
 [ 1  2  3  4]
 [ 5  6  7  8]]


hsplit() and vsplit() in Numpy  split the array into multiple sub array  horizontaly and verically


In [14]:
d=np.arange(1,13).reshape(3,4)
print(d,"\n")


#split the array into two parts equaly by column wise
split=np.hsplit(d,2)
print(split,"\n")


#split the array into three parts equaly by row wise
split1=np.vsplit(d,3)
print(split1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])] 

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


Solving Linear Regression Using Numpy

In [15]:
#suppose there are two euations
#2x+3y=20   and
#5x-4y=27  and problem is to find values of  x and y

a=np.array([[2,3],[5,-4]])
b=np.array([20,27])
res=np.linalg.solve(a,b)
print(res)

[7. 2.]


In [4]:
#8x+3y-2z=9    -4x+7y+5z=15    3x-4y-12z=35  in find values of x y and z
a=np.array([[8,3,-2],[-4,7,5],[3,-4,-12]])
b=np.array([9,15,35])
res=np.linalg.solve(a,b)
print(res)

[-1.82861897  4.60399334 -4.90848586]


Dot product of arrays are equivalent to the matrix multiplicaion in arrays.
The rows dimension from one matrix  must be same as column dimension in second array


In [8]:
a=np.array([[9,5,2],[1,8,5],[3,1,6]])
print(a.shape)
b=np.array([[3,2],[1,4],[5,3]])
print(b.shape)
ans=np.dot(a,b)
print(ans)

(3, 3)
(3, 2)
[[42 44]
 [36 49]
 [40 28]]


In [17]:
a=np.array([[2,3],[1,2]])
inv=np.linalg.inv(a)
print(a)
print(inv)
ans=np.dot(a,inv)
print(ans)


[[2 3]
 [1 2]]
[[ 2. -3.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]


Detrminant of Matrix array

In [20]:
w=np.array([[5,3],[2,4]])
print(w)
detr=np.linalg.det(w)
print(round(detr,2))

[[5 3]
 [2 4]]
14.0


Trace() - It will calculate the sum of primary diagonal elements

In [22]:
n=np.array([[3,6,2],[9,12,7],[22,18,15]])
print(n)
ans=np.trace(n)
print(ans)

[[ 3  6  2]
 [ 9 12  7]
 [22 18 15]]
30


Eigen values and Vectors-

This are defined only for the square matrix. The eigen vectors can not be zeros values may be equal to zeros

Av=Iλv

where a is square matrix 

λ is Eigen value 

v is Eigen vector 

det(a_λI)=0

In [24]:
n=np.array([[7,4],[5,9]])
e_val,e_vector=np.linalg.eig(n)
print(e_val)
print(e_vector)
# the dertminat have two values so there have two values for eigen vectors and values 

[ 3.41742431 12.58257569]
[[-0.74490545 -0.58243756]
 [ 0.66717004 -0.81287544]]
